name: CI - Build & Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Dynamic Tag
        id: tag
        run: echo "TAG=$(date +'%Y%m%d-%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build & Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:$TAG .
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-node-app:$TAG ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:$TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

      - name: Save Tag Info to Artifact
        run: echo $TAG > tag.txt